# Generated by Django 4.0.5 on 2022-06-13 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('primary_category_id', models.CharField(max_length=30)),
                ('secondary_category_id', models.CharField(max_length=30)),
                ('secondary_category_desc', models.TextField()),
                ('pcces_encode', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('image', models.TextField()),
                ('origin', models.CharField(max_length=50)),
                ('product_desc', models.TextField()),
                ('scope', models.CharField(max_length=30)),
                ('co2_allocation_id', models.CharField(max_length=30)),
                ('analytic_method_id', models.CharField(max_length=30)),
                ('emission_coefficient_source', models.CharField(max_length=30)),
                ('ISO_standard', models.CharField(max_length=30)),
                ('analysis_time_resource', models.CharField(max_length=30)),
                ('data_level', models.CharField(max_length=10)),
                ('product_flow_image', models.TextField()),
                ('company_name', models.CharField(max_length=512)),
                ('company_phone', models.CharField(max_length=30)),
                ('company_address', models.TextField()),
                ('company_mail', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField()),
                ('reviewer_name', models.CharField(max_length=512)),
                ('reviewer_phone', models.CharField(max_length=50)),
                ('reviewer_address', models.TextField()),
                ('reviewer_mail', models.CharField(max_length=50)),
                ('review_date', models.DateTimeField()),
                ('refresh_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
