# Generated by Django 4.0.5 on 2022-06-21 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrialcategory',
            name='primary_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industrial_categories', to='carbon_footprint_web.primarycategory'),
        ),
    ]
