# Generated by Django 4.0.5 on 2022-06-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
