# Generated by Django 4.0.5 on 2022-06-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint_web', '0002_alter_product_create_date_alter_product_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primary_category',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('category_id', models.CharField(max_length=30)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Secondary_category',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('primary_category_id', models.CharField(max_length=30)),
            ],
        ),
    ]
