# Generated by Django 4.0.5 on 2022-06-15 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint_web', '0003_primary_category_secondary_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondary_category',
            name='primary_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbon_footprint_web.primary_category'),
        ),
    ]
