# Generated by Django 4.0.5 on 2022-06-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint_web', '0004_alter_secondary_category_primary_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secondary_category',
            old_name='primary_category_id',
            new_name='primary_category',
        ),
    ]
