# Generated by Django 4.0.5 on 2022-06-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint_web', '0005_rename_primary_category_id_secondary_category_primary_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticMethod',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('method', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Co2Allocation',
            fields=[
                ('pcces_encode', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cradle_to_door', models.FloatField()),
                ('door_to_site', models.FloatField()),
                ('total_carbon_footprint', models.FloatField()),
                ('unit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DataLevel',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PccesEncode',
            fields=[
                ('pcces_encode', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('chapter', models.TextField()),
                ('six_desc', models.TextField()),
                ('senven_desc', models.CharField(max_length=50)),
                ('eight_desc', models.CharField(max_length=50)),
                ('nine_desc', models.CharField(max_length=50)),
                ('ten_desc', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Primary_category',
            new_name='PrimaryCategory',
        ),
        migrations.RenameModel(
            old_name='Secondary_category',
            new_name='SecondaryCategory',
        ),
    ]
