# Generated by Django 4.0.5 on 2022-06-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint_web', '0006_analyticmethod_co2allocation_datalevel_pccesencode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co2allocation',
            name='cradle_to_door',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='co2allocation',
            name='door_to_site',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='co2allocation',
            name='total_carbon_footprint',
            field=models.FloatField(null=True),
        ),
    ]
