# Generated by Django 4.0.5 on 2022-06-16 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint_web', '0007_alter_co2allocation_cradle_to_door_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='analytic_method_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='co2_allocation_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='primary_category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='secondary_category_id',
        ),
        migrations.AddField(
            model_name='product',
            name='analytic_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carbon_footprint_web.analyticmethod'),
        ),
        migrations.AddField(
            model_name='product',
            name='co2_allocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carbon_footprint_web.co2allocation'),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carbon_footprint_web.primarycategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carbon_footprint_web.secondarycategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carbon_footprint_web.datalevel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_flow_image',
            field=models.ImageField(upload_to='product_flow_image'),
        ),
    ]
