# Generated by Django 4.0.5 on 2022-06-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint_web', '0008_remove_product_analytic_method_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_flow_image',
            field=models.ImageField(upload_to='product_flow_image/'),
        ),
    ]
